apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: l0y7ahm6g-java-springboot
  janus-idp.io/tekton: l0y7ahm6g-java-springboot
  backstage.io/kubernetes-id: l0y7ahm6g-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: l0y7ahm6g-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
